# 1. Data Science 

1. Drew Conway: Hacking skills, Math and statistics Knowledge, Substantive expertise + Scientific inquiry
2. David Donoho
<br>
 (1) Data Exploration and Preparation
 <br>
 (2) Data Representation and Transformation
 <br>
 (3) Computing with Data
 <br>
 (4) Data Modeling: Generative modeling / Predictive modeling
 <br>
 (5) Data Visualization and Presentation
 <br>
 (6) Science about Data Science

# 2. The Python Programming Language 
## 1. Functions

### 파이썬 함수의 특징 
- You don't have to set return type
- You don't have to set user return statement
- You can assign a variable to a function
- 매개변수(parameter)에 디폴트값을 설정할 수 있음
<br>
1.디폴트값을 설정한 매개변수는 function declaration 마지막에 위치
<br>
2.Useful when printing out multiple values for a single cell

#### 1. 매개변수에 디폴트값 설정하기 

In [1]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


#### 2. Assign a variable to a function

In [2]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

## 2. Types and Sequences

### (1) Tuple and List

- Tuple : ()을 사용, 변경 불가능(immutable)
- List : []을 사용, 변경 가능(mutable)

#### 1. Indexing operator '[ ]'를 통해 리스트/튜플의 데이터값에 접근

In [3]:
a = [1, 2, 3, 4, 5]
a[2]

3

#### 2. max, min, len 함수

In [4]:
print(max(a))
print(min(a))
print(len(a))

5
1
5


#### 3. +(연결), *(반복), in(해당 데이터가 있는지 확인)

In [3]:
(1,2) + (3,4)

(1, 2, 3, 4)

In [6]:
[1,2] * 3

(1, 2, 1, 2, 1, 2)

In [7]:
1 in [1, 2, 3]

True

#### 4. Iterable types: Loops (for, while) 를 사용할 수 있음

In [8]:
x = [1, 'a', 2, 'b']

for item in x:
    print(item)

1
a
2
b


#### 5. Slicing: [ starting location : the end of the slice ] 을 통해 슬라이싱

In [9]:
x = [1, 2, 3, 4, 5]
print(x[0]) 
print(x[0:2])
print(x[-1])
print(x[:3])

1
[1, 2]
5
[1, 2, 3]


#### 6. Unpacking: 리스트/튜플의 데이터를 여러 변수에 각각 저장

In [10]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [11]:
print(fname)
print(lname)

Christopher
Brooks


### (2) Strings
#### 1. split( ): 문자열을 나누고, 나눠진 값들을 하나의 리스트에 저장

In [9]:
List = 'Christopher Arthur Hansen Brooks'.split(' ') # ' '을 기준으로 문자열을 나눔
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list

print(List)
print(firstname)
print(lastname)

['Christopher', 'Arthur', 'Hansen', 'Brooks']
Christopher
Brooks


#### 2. format ( ): 숫자를 문자열로 변환하기 위해 매번 str( )을 사용하기는 번거로울때 사용할 수 있음

In [7]:
sales_record = {'price': 3.24,'num_items': 4,'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


### (3) Dictionary 
- {keys:values}의 형태
- 사전에 있는 아이템들 간의 순서가 존재하지 않음

In [1]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}

#### 1. dic[key]: key에 대한 value 값을 반환

In [3]:
x['Christopher Brooks'] 

'brooksch@umich.edu'

#### 2. 새로운 아이템 추가: dic[key] = value

In [4]:
x['Kevyn Collins-Thompson'] = None
x

{'Christopher Brooks': 'brooksch@umich.edu',
 'Bill Gates': 'billg@microsoft.com',
 'Kevyn Collins-Thompson': None}

#### 3. 모든 key를 반복

In [5]:
for name in x:
    print(name)

Christopher Brooks
Bill Gates
Kevyn Collins-Thompson


In [6]:
for name in x.keys(): #x.keys(): 사전의 keys들만 저장해놓은 리스트를 생성
    print(name)

Christopher Brooks
Bill Gates
Kevyn Collins-Thompson


#### 4. 모든 value를 반복

In [16]:
for email in x.values(): #x.values(): 사전의 value들만 저장해놓은 리스트를 생성
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


#### 5. 모든 item을 반복

In [17]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


## (3) Dates and Times

In [9]:
#get the current time since the epoch(1970년 1월 1일)

import datetime as dt
import time as tm 

#### 1. time( ) : return current time in seconds 

In [10]:
tm.time()

1568699669.8959649

#### 2. Datetime로 변환하기 

In [11]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2019, 9, 17, 14, 54, 31, 532231)

In [22]:
# Get year, month, day, etc.from a datetime

dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second 

(2019, 8, 7, 16, 4, 33)

#### 3. `date.today`: 오늘 날짜를 알려줌

In [13]:
today = dt.date.today()
print(today)

2019-09-17


#### 4. `timedelta` : 두 날짜간의 차이

In [14]:
delta = dt.timedelta(days = 100) 

# 오늘로부터 100일 전 날짜
today - delta 

100 days, 0:00:00


datetime.date(2019, 6, 9)

## (4) Objects and map( )

#### 1. Class and Objects

In [15]:
class Person:
    department = 'School of Information' # 모든 object의 공통된 속성

    def set_name(self, new_name): # 각 object의 속성 정하기
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [16]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


#### 2. map( )
- map(function, iterable1. iterable2, ...)의 형태. (iterable: list, tuple, dictionary...)
- Function is applied to the items from all iterables 'in parallel'
- With mutiple iterables, the iterator stops when the shortest iterable is exhausted


- Map function returns map object

In [27]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

- Maps are iterable, so we can use a for loop to look at all of the values in the map

In [28]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


## (5) Lambda and List Comprehensions

#### 1. Lambda
- anonymous function
- single line expression
- 디폴트값을 설정할 수 없음
- 복잡한 로직을 가질 수 없음

In [17]:
my_function = lambda a, b, c : a + b
my_function(1, 2, 3)

3

#### 2. List comprehension: more abbreviated syntax를 이용해 리스트, 튜플, 사전 만들기

In [30]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [31]:
# List comprehension을 이용한 경우

my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

## (5) Numerical Python (NumPy)

In [1]:
import numpy as np

### 1. array 생성하기
#### (1) np.array

In [2]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [3]:
m.shape

(2, 3)

#### (2) np.arange(start, stop, stepsize)

In [4]:
n = np.arange(0, 30, 2) 
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### (3) np.linspace(start, stop, array에 들어갈 숫자의 개수)

In [36]:
o = np.linspace(0, 4, 9) 
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

#### (4) 그 외

In [37]:
x = np.ones((3, 2)) #모든 값이 1인 3행 2열의 array
print(x)

y = np.zeros((2, 3))#모든 값이 0인 2행 3열의 array
print(y)

z = np.eye(3) #대각선의 값이 3개인 array
print(z)

u = np.array([1,2,3]) 
np.diag(u) # array의 값을 대각선 위치에 지니는 새로운 array

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### (5) np.repeat

In [38]:
np.array([1, 2, 3] * 3) #리스트 자체를 3번 반복

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
np.repeat([1, 2, 3], 3) #행렬의 각 숫자를 3번씩 반복

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### 2. reshape and resize
- 공통점: array의 크기를 변환
- 차이점: reshape는 원본을 변경하지 않음, resize는 원본을 변경

In [40]:
a = np.arange(0, 30, 2)
n = a.reshape(3, 5) #3행 5열의 array로 변경
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [41]:
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [42]:
o.resize(3, 3) #3행 3열의 array로 변경
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [43]:
print(o)

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]


### 3. Combining Arrays
- `vstack` : stack arrays in sequence vertically (row wise)
- `hstack`: stack arrays in sequence horizontally (column wise)

In [44]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### 4. Operation

In [47]:
x = np.array([1,2,3])
y = np.array([4,5,6])

- +(덧셈), -(뺄셈), * (곱셈), /(나눗셈), ** (제곱) 

In [48]:
print(x + y) # array의 값들 간의 덧셈 [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # array의 값들 간의 뺄셈  [1 2 3] - [4 5 6] = [-3 -3 -3]

print(x * y) # array의 값들 간의 곱셈  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # array의 값들 간의 나눗셈  [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

print(x**2) # array의 값들에 대해 제곱  [1 2 3] ^2 =  [1 4 9]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


- Dot Product: 두 가지 행렬을 곱하는 것과 같은 방식

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3 $


In [49]:
print(x.dot(y))
print(np.dot(x,y))

32
32


### 5. Transposing array

- array의 행,열을 서로 바꿈

In [50]:
import numpy as np

z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [51]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

### 6. dtype, astype
- dtype: 데이터 타입 확인
- astype: 데이터 타입 바꾸기

In [52]:
z.dtype

dtype('int32')

In [53]:
z = z.astype('f') 
z.dtype

dtype('float32')

### 7. Math Functions

#### (1) sum, max, min, mean, std

In [54]:
a = np.array([-4, -2, 1, 3, 5])
print(a.sum())
print(a.max())
print(a.mean())
print(a.std())

3
5
0.6
3.2619012860600183


#### (2) `argmax` 와 `argmin` 는 최대값, 최솟값의 index를 반환

In [55]:
a.argmax()

4

### 8. Indexing and Slicing

In [56]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [57]:
r[2, 2]

14

In [58]:
r[3, 3:6] 

array([21, 22, 23])

In [59]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [60]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### 9. Copying Data
- Be careful with copying and modifying arrays in NumPy!

In [61]:
r2 = r[:3,:3]
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
r #원래 array도 변화

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

- 원래 array도 변하는 것을 막기 위해선, `.copy`로 copy를 만들어야함 

In [63]:
r_copy = r.copy()
r_copy[:] = 10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [64]:
r #원래 array는 변화하지 않음

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### 10. Array 반복하기

In [65]:
#create a new 4 by 3 array of random numbers 0-9

test = np.random.randint(0, 10, (4,3)) 
test

array([[4, 5, 4],
       [6, 2, 4],
       [3, 1, 8],
       [3, 8, 1]])

#### (1) 행을 반복하기

In [66]:
for row in test:
    print(row)

[4 5 4]
[6 2 4]
[3 1 8]
[3 8 1]


#### (2) 행과 index 반복하기

In [67]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [4 5 4]
row 1 is [6 2 4]
row 2 is [3 1 8]
row 3 is [3 8 1]


#### (3) Use `zip` to iterate over multiple iterables.

In [68]:
test2 = test**2
test2

array([[16, 25, 16],
       [36,  4, 16],
       [ 9,  1, 64],
       [ 9, 64,  1]], dtype=int32)

In [69]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[4 5 4] + [16 25 16] = [20 30 20]
[6 2 4] + [36  4 16] = [42  6 20]
[3 1 8] + [ 9  1 64] = [12  2 72]
[3 8 1] + [ 9 64  1] = [12 72  2]
